### ISSUE TITLE
La lista de reproducción se detiene 

### ISSUE THREAD

**Issue by ingmgumbs** [wilsonhamiltond/music-streaming#13]
La lista de reproducción de un PL previamente guardado, se detiene cuando se suena una canción y no continua a la siguente.

**Comment by wilsonhamiltond** [comment]
Fixes in commit https://github.com/wilsonhamiltond/music-streaming/commit/972f083e8b590e1161a2b7114067d6eeb6f2c811
Verify

**Comment by ingmgumbs** [comment]
FIXED
